name: Check

on:
  - push
  - pull_request

jobs:
  shellchecker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shell Formatter
        uses: luizm/action-sh-checker@v0.3.0
        env:
          SHFMT_OPTS: -i 2

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
